[WIP] Feat/CU-k7ctmn Filtro Perfiles
hifrontendcafe/website pull request #179
Opened 2021-05-23 17:46 UTC by hercase

❎ Feature en proceso

![image](https://user-images.githubusercontent.com/5130752/119270957-a4aa8980-bbd5-11eb-92fa-635957e153aa.png)

2021-05-23 17:46 UTC, hifrontendcafe commented
Task linked: [CU-k7ctmn Perfiles - Implementar Filtros para las tecnologíaas](https://app.clickup.com/t/k7ctmn)

2021-05-23 18:21 UTC, mobregozo approved these changes

2021-05-25 18:02 UTC, marbiano requested changes
Code looks good to me, but overall I feel like it's complex enough to deserve some comments all around, especially because this is a team effort and somebody else might need to work on this in the future.

2021-05-25 18:02 UTC, marbiano commented on src/pages/comunidad/index.tsx
> +                    intersection(
While I understand the need for this, I feel like it's pretty complex and should be:

1. Abstracted into a function or component of its own.
2. Commented so other people can understand what it does without spending too much time looking for 3rd part toold docs.

2021-05-25 18:26 UTC, closed without merging