fix(reactivistas): fix input placeholder text color
hifrontendcafe/website pull request #184
Opened 2021-05-26 16:18 UTC by EzequielCaste

![image](https://user-images.githubusercontent.com/51804994/119695742-debd9a80-be24-11eb-9a7b-ab5e3940cafa.png)

2021-05-26 16:18 UTC, hifrontendcafe commented
Task linked: [CU-4x5uv4 Reactivistas: En mobile el input de texto se ve gris](https://app.clickup.com/t/4x5uv4)

2021-05-27 16:03 UTC, mobregozo requested changes
As we agreed, the input of the date is the one that needs to be changed.

2021-05-27 19:02 UTC, EzequielCaste commented
the input date is no longer gray
![image](https://user-images.githubusercontent.com/51804994/119882412-c91fa200-bf04-11eb-9ffd-53a7d92bc973.png)

the calendar appears in mobile
![image](https://user-images.githubusercontent.com/51804994/119882524-e48aad00-bf04-11eb-96fd-0ceeb272eb32.png)

2021-05-27 20:39 UTC, mobregozo approved these changes

2021-05-27 21:55 UTC, merged